global:
  num_workers: 0

ogbn-arxiv:
  common:
    batch_size: 512

  MLP:  
  MLP3w4:
    num_layers: 3
    hidden_dim: 1024
    
  SAGE:  
    fan_out: 5,10,15
  
ogbn-products: 
  common:
    batch_size: 512
    num_workers: 8
    patience: 30

  MLP: 
  MLP3w8:
    num_layers: 3
    hidden_dim: 2048
    
  SAGE:  
    fan_out: 5,10,15


  

      
  
